### ISSUE TITLE
On Mac M1, I get an import error related to numba

### ISSUE THREAD

**Issue by josh-ashkinaze** [krishnanlab/PecanPy#139]
`ImportError: cannot import name '_get_thread_id' from 'numba.np.ufunc.parallel' (/Users/jashkina/Library/Python/3.8/lib/python/site-packages/numba/np/ufunc/parallel.py)`

**Comment by josh-ashkinaze** [comment]
It is fixed when downgrading to numba to 0.55.2. Just wanted other folks to be aware. And I also added this bug on the numba side.

**Comment by RemyLau** [comment]
Hi @josh-ashkinaze thanks for pointing this out! I will add a requirement to `numba<0.56`
