### ISSUE TITLE
What happens after simulate_walks?

### ISSUE THREAD

**Issue by jimmy-academia** [krishnanlab/PecanPy#18]
In the example given in https://pecanpy.readthedocs.io/en/latest/pecanpy.html#module-pecanpy.node2vec, 
it reads "# at this point, the random walks could be fed to w2v to generate embeddings"
however, I am not clear how and which w2v should be utilized?
Could you provide perhaps a preferred word2vec package?

Thank you!

**Comment by RemyLau** [comment]
Hi @jimmy-academia, PecanPy uses [gensim](https://radimrehurek.com/gensim/) for runing word2vec, as could be seen in the command line interface script

https://github.com/krishnanlab/PecanPy/blob/fe4f2c1865fe0e28d431cf8ff89456b825d69ede/src/pecanpy/cli.py#L183-L206
