### ISSUE TITLE
Reg Multi Processing

### ISSUE THREAD

**Issue by KarthikRevanuru** [krishnanlab/PecanPy#21]
Does the library automatically detect number of cores and parellize or do we have to specify ? If we have to specify how to do that ?

**Comment by RemyLau** [comment]
Yes, the default number of processes is 8. If you specify `--workers` to be `0`, it uses all available cores in the system.

https://github.com/krishnanlab/PecanPy/blob/6a0a73312b99ec476a4d397159becf5e210ab48f/src/pecanpy/cli.py#L71-L75

Essentially, this is done by setting the number of processes to `numba.config.NUMBA_DEFAULT_NUM_THREADS `, which is determined based on `multiprocessing.cpu_count()` (see more in the [Numba documentation](https://numba.pydata.org/numba-doc/latest/user/threading-layer.html#numba.config.NUMBA_DEFAULT_NUM_THREADS))

https://github.com/krishnanlab/PecanPy/blob/6a0a73312b99ec476a4d397159becf5e210ab48f/src/pecanpy/cli.py#L225-L227

So for example, you can run pecanpy using all available nodes as:

```bash
$ pecanpy --input path_to_input_edgelist --output path_to_output_embedding --workers 0
```
