### ISSUE TITLE
Using Rejection Sampling

### ISSUE THREAD

**Issue by KarthikRevanuru** [krishnanlab/PecanPy#22]
@RemyLau what are your thoughts on rejection sampling used here https://github.com/louisabraham/fastnode2vec ?

**Comment by RemyLau** [comment]
Not sure what's new there, but under the hood this is what PecanPy does for the OTF modes (`SparseOTF`, and `DensOTF`). 

See sampling function for `SparseOTF`

https://github.com/krishnanlab/PecanPy/blob/6a0a73312b99ec476a4d397159becf5e210ab48f/src/pecanpy/node2vec.py#L368-L377

and `DenseOTF`

https://github.com/krishnanlab/PecanPy/blob/6a0a73312b99ec476a4d397159becf5e210ab48f/src/pecanpy/node2vec.py#L415-L424
