### ISSUE TITLE
'simulate_walks' is adding one additional node to total walk length

### ISSUE THREAD

**Issue by amjass12** [krishnanlab/PecanPy#243]
Hi!

I am running Word2Vec on graphs generated from networkx and cam using PecanPy in python to simulate walks and then run word2vec. I am finding that during the `simulate_walks` function, the length of the walk is always 1 node + the total `walk_length`. Is there a reason for this behaviour or is this a bug?

The code that I am using is as follows:
```
nx.write_edgelist(graph, 'test_edgelist.edg', delimiter=' ', data=False)
g = node2vec.PreComp(p=0.7, q=1, workers=12, verbose=True)
g.read_edg('test_edgelist.edg', 
           weighted=False, directed=False, delimiter=' ')

g.preprocess_transition_probs()
walks = g.simulate_walks(num_walks=200, walk_length=30)
print(len(walks[0]))
>>> 31

#train model (do this using gensim myself as need access to whole model)

from gensim.models import Word2Vec
model = Word2Vec(walks)
```
all of the walks are the walk_length + 1 - whatever number i specify and also if i run this on the karate example dataset. 

Any idea what is happening here - is this behaviour expected?

I have also found that `simulate_walks` run without triggering `g.preprocess_transition_probs()`, again, is there an explanation for this behaviour?

many thanks!

many thanks!

**Comment by RemyLau** [comment]
Hi @amjass12. Yes, `walk_length + 1` is the right length for the walk. The first entry in each random walk sequence is the "seed" node for that random walk, i.e., the walk starts from there. Another way to think about this is that these random walks are "node-sequences". So, the number of transitions in a sequence of length "k" is "k - 1".

In terms of `preprocess_transition_probs`, you don't have to manually call it as it will check if the preprocessing has been done internally and call it automatically if not.

**Comment by amjass12** [comment]
Hi @RemyLau , 

Thank you very much for that clear explanation! all makes perfect sense!

A quick follow up: in this line:

```
from pecanpy import pecanpy as node2vec
nx.write_edgelist(graph, 'test_edgelist.edg', delimiter=' ', data=False)
g = node2vec.PreComp(p=0.7, q=1, workers=12, verbose=True)
g.read_edg('test_edgelist.edg', 
           weighted=False, directed=False, delimiter=' ')

```

node2vec.PreComp (which is for small graphs) is followed by g.read_edg('etc')

is this line:
```
g.read_edg('test_edgelist.edg', 
           weighted=False, directed=False, delimiter=' ')

```
exactly the same if I do:
`g = node2vec.SparseOTF(p=0.7, q=1, workers=12, verbose=True)
`
and
`g = node2vec.DenseOTF(p=0.7, q=1, workers=12, verbose=True)`

or does read_edg need to be different in any other format for example after DenseOTF. I have graphs of various sizes including extremely dense graphs. 

Also, does the % of edges advice, correspond to % of total number of nodes?

for example, the advice is use DenseOTF if there are more than 10000 nodes and >10% edges - what does **>10% edges** refer to here? thank you so much!

**Comment by RemyLau** [comment]
You can use `g.read_edge` exactly the same way for any mode, including `SparseOTF` and `DenseOTF`.

The % of edges means the [density](https://www.baeldung.com/cs/graph-density#:~:text=Graph%20density%20represents%20the%20ratio,in%20terms%20of%20edge%20connectivity.) of the graph, which is computed as

$Density(G) = \frac{Num. edges}{Num. nodes * (Num. nodes - 1)}$

where the denominator is the number of edges of a fully connected graph with $Num. nodes$ number of nodes (without self-loops).

**Comment by amjass12** [comment]
Thank you! in the case where the graph is not fully connected or directed (i.e, there are communities of nodes connected across each other, for example 500 nodes interconnected but not connected to other nodes on the graph) can the same equation be used to roughly estimate the density?

**Comment by RemyLau** [comment]
Yes the density equation can be applied.

However, it is typically not advised to trivially apply node2vec to _disconnected_ graphs, as the numerical relationships (e.g., inner products) of embeddings of nodes between two disconnected components do not make much sense. In the case of disconnected graphs, it would be better to analyze each component independently or somehow find a way to connect all these components together before proceeding.

**Comment by amjass12** [comment]
Hi @RemyLau ,

Many thanks! Yes isolated nodes are relatively rare and the embeddings of nodes are still very powerful with respect to their surrounding environment - but yes, i am aware of this caveat and have proceeded on that basis :) many thanks!
