### ISSUE TITLE
Release under an open source license

### ISSUE THREAD

**Issue by dhimmel** [krishnanlab/PecanPy#3]
Currently the repository is released under a CC BY-NC-SA 4.0 License as per [LICENSE.md](https://github.com/krishnanlab/pecanpy/blob/babc2b6b5b43b0cb3f3881e7a54bc7e0cea89806/LICENSE.md).

This is a very restrictive license that is incompatible with other licenses and is not designed for software.

If the goal is to create an open source software package that researchers can use and improve upon, then I'd recommend an OSI-approved license at https://opensource.org/licenses.

For Python packages, the BSD Licenses are popular. I personally use the [BSD-2-Clause Plus Patent License](https://spdx.org/licenses/BSD-2-Clause-Patent). This license is [OSI-approved](https://opensource.org/licenses/BSDplusPatent) and [rated highly](https://blueoakcouncil.org/list) for its simplicity, compatability, and effectiveness.

Happy to answer any license questions.

As a potential user of this package, I am wary to consider it further until it has a license to ensure a sustainable future and open exisitence!

**Comment by arjunkrish** [comment]
@dhimmel Thanks for bringing this up. We would very much like to create an open-source software package that researchers can use and improve upon. So, I would like to change the license appropriately. Do you have an example LICENSE.md file that I can look at to change our license?

**Comment by arjunkrish** [comment]
@dhimmel Actually, I think I fixed this (and decided to go with BSD-3-Clause).
Hope this [LICENSE](https://github.com/krishnanlab/PecanPy/blob/master/LICENSE.md) works.

**Comment by arjunkrish** [comment]
Code now released under BSD-3-Clause
