### ISSUE TITLE
TypeError: simulate_walks() missing 2 required positional arguments: 'n_ckpts' and 'pb_len'

### ISSUE THREAD

**Issue by belma-m** [krishnanlab/PecanPy#54]
Hi,

with the version 2.0.1 there emerged this issue:

_TypeError: simulate_walks() missing 2 required positional arguments: 'n_ckpts' and 'pb_len'_

Once I downgraded to 2.0.0, it worked as before.

**Comment by RemyLau** [comment]
Hi @belma-m, thanks for reporting! Could you provide a little more info about your setup and the traceback? I've tested a couple of cli use cases but did not encounter this issue. Could you share the script that causes this so I can try to run and explore a little bit more myself? Thanks!

**Comment by RemyLau** [comment]
Hi, @belma-m I've found the issue. This should be fixed by a recent PR #51. I'll close this now, but feel free to follow up if you still encounter any further issues!

**Comment by RemyLau** [comment]
I've just released version 2.0.2, which contains the patch that fixes the error above.
