### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by eric-czech** [krishnanlab/PecanPy#83]
Hey @RemyLau, do you have any plans for a release in the near future?  It would be great if one beyond 2.0.2 included some changes like https://github.com/krishnanlab/PecanPy/pull/71 and https://github.com/krishnanlab/PecanPy/pull/78 .

**Comment by RemyLau** [comment]
Hi @eric-czech, that's a good idea! I'm always used to just using the dev branch and forgetting about the release... I'll do that today!

**Comment by RemyLau** [comment]
PecanPy v2.0.3 is out! https://github.com/krishnanlab/PecanPy/releases/tag/v2.0.3

**Comment by eric-czech** [comment]
Thanks @RemyLau!
