### ISSUE TITLE
nptyping not in setup.cfg

### ISSUE THREAD

**Issue by eric-czech** [krishnanlab/PecanPy#93]
Hey @RemyLau, the [2.0.3](https://pypi.org/project/pecanpy/2.0.3/) package doesn't have nptyping in `install_requires` of setup.cfg so new installations don't import.  They break at https://github.com/krishnanlab/PecanPy/blob/bb6b09ac036ffa175e0d184a386daec3a0cd8ccd/src/pecanpy/typing.py#L11

**Comment by RemyLau** [comment]
@eric-czech thanks for the catch! I just added that to the ``setup.cfg`` file. But I'll probably not create another patch for this. For now, manually installing nptying should be fine ``pip install nptying``

**Comment by RemyLau** [comment]
Closing with PecanPy 2.0.5 https://github.com/krishnanlab/PecanPy/releases/tag/v2.0.5
